### ISSUE TITLE
License

### ISSUE THREAD

**Issue by spaghetsie** [Legendkiller21/MAS-Submods#4]
Hey,
I've accidentaly stumbled upon this and I do agree that it should be a feature by default.
But seeing how there is no license I was wondering how you feel about this being used in other mods. Namely JustNatsuki.

Any response appreciated, take care!

**Comment by Legendkiller21** [comment]
Sure go ahead, although, please leave credit to me and LordBaaa if you're going to use it. 

Fair warning, it **doesn't** play nicely with renpy's input. Because of that and that it is usually used only by devs, and users who really need to paste something big, like a link, I would personally keep it as a submod.

**Comment by spaghetsie** [comment]
Alright, thank you!
